main/forms/__init__.py
from main.forms.add_posts import AddPost
from main.forms.register import RegisterForm
from main.forms.login import LoginForm

main/forms/add_posts.py
from wtforms import Form, StringField, TextAreaField, validators

class AddPost(Form):
	title = StringField('Title', [validators.Length(min=1, max=255)])
	content = TextAreaField('Content', [validators.Length(min=1)])

main/forms/login.py
from wtforms import Form, StringField, PasswordField, validators


class LoginForm(Form):
	"""Login form for User."""
	email = StringField('Email', [validators.Length(min=1)])
	password = PasswordField('Password', [validators.Length(min=1)])

main/forms/register.py
"""USer Registeration Form."""
from wtforms import Form, StringField, PasswordField, validators, ValidationError
from main.models import User


class RegisterForm(Form):
    """User Registeration Form."""

    name = StringField('Name', [validators.Length(min=1, max=255)])
    email = StringField('Email', [validators.Length(min=1, max=255)])
    password = PasswordField('Password', [validators.DataRequired(), validators.EqualTo('confirm', message="Password didn\'t matched!!!")])
    confirm = PasswordField('Confirm Password', [validators.Length(min=1)])

    def validate_email(self, email):
    	user = User.query.filter_by(email=email.data).first()
    	if user:
    		raise ValidationError('That email is already taken. Please choose a different email!!')

main/views/add_post.py
"""Add Post business logic."""
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from main import db
from main.forms import AddPost
from main.models import Post

post_bp = Blueprint('post_bp', __name__)


@post_bp.route('/post', methods=['GET', 'POST'])
@login_required
def add_post():
    """Add Post view."""
    form = AddPost(request.form)
    if request.method == 'POST' and form.validate():
            title = request.form['title']
            content = request.form['content']
            new_post = Post(title, content, current_user.id)
            db.session.add(new_post)
            try:
                db.session.commit()
                flash('Comments are posted successfully', 'success')
                return redirect(url_for('dashboard_bp.dashboard'))
            except:
                flash('Comments couldn\'t got posted', 'danger')
                return render_template('add_posts.html', form=form)
    return render_template('add_posts.html', form=form)

main/views/logout.py
from flask import Blueprint, request, render_template, flash, redirect, url_for, session
from flask_login import login_required, logout_user


logout_bp = Blueprint('logout_bp', __name__)

@logout_bp.route('/logout')
@login_required
def logout():
	session.clear()
	logout_user()
	flash('You have succesfully logged out.', 'success')
	return redirect(url_for('dashboard_bp.dashboard'))

main/views/profile.py
from flask import Blueprint, render_template
from flask_login import current_user, login_required
from main.models import User, Post

profile_bp = Blueprint('profile_bp', __name__)


@profile_bp.route('/profile')
@login_required
def profile():
	"""Author profile page."""
	author = User.query.get(current_user.id)
	return render_template('profile.html', author=author)

main/templates/includes/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}  

main/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}  

main/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link font-weight-bold" href="{{ url_for('dashboard_bp.dashboard') }}">Dashboard</a>
      </li>
      <li class="nav-item">
        <a class="nav-link font-weight-bold" href="{{ url_for('post_bp.add_post') }}">Add Comments</a>
      </li>
    </ul>
    <ul class="ml-auto navbar-nav">
      {% if not session.logged_in %}
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{ url_for('register_bp.register') }}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{ url_for('login_bp.login') }}">Login</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{ url_for('profile_bp.profile') }}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link font-weight-bold" href="{{ url_for('logout_bp.logout') }}">Logout</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>